trigger:
- none  # No se ejecuta automáticamente

pool:
  name: Default
  demands:
    - agent.name -equals DESKTOP-DJKAGKC

steps:
- checkout: self

- script: |
    echo "Authenticating with Debricked..."
    C:\Temp\cli_windows_x86_64\debricked.exe auth token --access-token $(DEBRICKED_TOKEN) || exit 1

    echo "Scanning code..."
    C:\Temp\cli_windows_x86_64\debricked.exe scan --directory .
  displayName: 'Debricked scan with binary CLI'
