trigger: none
pr: none

pool:
  name: Default
  demands:
    - agent.name -equals DESKTOP-DJKAGKC

steps:
- checkout: self

- script: |
    echo Running Debricked scan using pre-installed CLI
    set DEBRICKED_TOKEN=$(DEBRICKED_TOKEN)
    echo ===== AGENT CONTEXT =====
    whoami

    echo ===== CURRENT DIRECTORY =====
    cd

    echo ===== PATH =====
    echo %PATH%

    echo ===== WHERE DEBRICKED =====
    where.exe debricked

    echo ===== DEBRICKED VERSION =====
    debricked -v

    echo ===== DIRECT PATH =====
    debricked -v
    debricked scan .
  displayName: 'Debricked scan with pre-installed CLI'
