# Maven
 
trigger:
- main
 
pool:
  name: Default
  demands:
  - agent.name -equals DESKTOP-DJKAGKC
 
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
- task: FortifyOnDemandStatic@9
  inputs:
    FortifyProjects: 
    FodConnection: 'FoD_AzureDevOps'
    ReleaseOptions: '0'
    ReleaseId: 1457130
    EntitlementSelection: '0'
    Entitlement: 13738
    EntitlementPreference: '2'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '0'
    BuildType: 'mvn'
    BuildCommand: 'clean package'
    PolicyFailAction: '0'

# Debricked
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install --upgrade pip
    pip install debricked-cli
  displayName: 'Install Debricked CLI'

- script: |
    echo "Logging into Debricked..."
    debricked login --token $(DEBRICKED_TOKEN)

    echo "Running Debricked scan..."
    debricked scan --ci azureDevOps --directory .
  displayName: 'Run Debricked CLI scan'    