trigger:
- none  # No se ejecuta automáticamente

pool:
  name: Default
  demands:
    - agent.name -equals DESKTOP-DJKAGKC

steps:
- checkout: self

- script: |
    echo "Setting environment variable for Debricked token"
    set DEBRICKED_TOKEN=$(DEBRICKED_TOKEN)

    echo "Running Debricked scan without interactive login..."
    C:\Temp\cli_windows_x86_64\debricked.exe scan --directory .
  displayName: 'Debricked scan using token env var'

