name: Java CI with Debricked Scan v1

# Ejecutar solo manualmente
on:
  workflow_dispatch:

jobs:
  debricked-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Debricked Scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -e DEBRICKED_TOKEN=${{ secrets.DEBRICKED_TOKEN }} \
            ghcr.io/debricked/cli:latest scan /src --upload

      - name: Save report
        run: |
          mkdir -p reports
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            -e DEBRICKED_TOKEN=${{ secrets.DEBRICKED_TOKEN }} \
            ghcr.io/debricked/cli:latest report /src --format json --output /src/reports/debricked-report.json

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: debricked-report
          path: reports/debricked-report.json

      - name: Fail if critical/high vulnerabilities
        run: |
          CRITICAL=$(jq '.summary.critical' reports/debricked-report.json)
          HIGH=$(jq '.summary.high' reports/debricked-report.json)
          echo "Found CRITICAL=$CRITICAL HIGH=$HIGH"
          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
            echo "❌ Vulnerabilities found! Failing the job."
            exit 1
          fi
